<script type="text/javascript" src="../assets/js/jquery.js"></script>
<script type="text/javascript" src="../assets/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="../assets/js/smoothscroll.js"></script>
<script type="text/javascript" src="../assets/js/jquery.isotope.min.js"></script>
<script type="text/javascript" src="../assets/js/jquery.prettyPhoto.js"></script>
<script type="text/javascript" src="../assets/js/jquery.parallax.js"></script>
<script type="text/javascript" src="../assets/js/main.js"></script>
<script type="text/javascript" src="../assets/js/lumino.glyphs.js"></script>
<script type="text/javascript" src="assets/js/getUrlParam.js"></script>
<script type="text/javascript" src="assets/js/traitement_get.js"></script>
